{
 "title": "Pizza Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Logging",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  },
  {
   "title": "HTTP requests/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "http_request_total_requests{source=\"jwt-pizza-service\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "http_delete_requests{source=\"jwt-pizza-service\"}",
     "legendFormat": "Delete"
    },
    {
     "expr": "http_get_requests{source=\"jwt-pizza-service\"}",
     "legendFormat": "Get"
    },
    {
     "expr": "http_post_requests{source=\"jwt-pizza-service\"}",
     "legendFormat": "Post"
    },
    {
     "expr": "http_put_requests{source=\"jwt-pizza-service\"}",
     "legendFormat": "Put"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pizza_revenue_bitcoin{source=\"jwt-pizza-service\"}",
     "legendFormat": "Revenue"
    }
   ]
  },
  {
   "title": "Pizza Creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "pizza_creation_latency_milliseconds{source=\"jwt-pizza-service\"}",
     "legendFormat": "Creation Latency"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "active_users{source=\"jwt-pizza-service\"}",
     "legendFormat": "Active Users"
    }
   ]
  },
  {
   "title": "Pizza Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "http_post_latency_milliseconds{source=\"jwt-pizza-service\"}",
     "legendFormat": "Request Latency"
    }
   ]
  },
  {
   "title": "Pizza Purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "pizza_sold_pizzas{source=\"jwt-pizza-service\"}",
     "legendFormat": "Sold"
    },
    {
     "expr": "pizza_creation_failures{source=\"jwt-pizza-service\"}",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "CPU | Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage_percentage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "memory_usage_percentage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "auth_successful_attempts{source=\"jwt-pizza-service\"}",
     "legendFormat": "Success"
    },
    {
     "expr": "auth_failed_attempts{source=\"jwt-pizza-service\"}",
     "legendFormat": "Failed"
    }
   ]
  }
 ]
}